### ISSUE TITLE
undeclaredCompileDependencies does not take into account appended deps

### ISSUE THREAD

**Issue by manuelcueto** [cb372/sbt-explicit-dependencies#42] opened 2019-10-08 10:52 UTC
In our multi-module project we have a structure like: 
```
- core/
- tools/
```
and in our project root we have a dependencies file where we define all our deps. then in each module's build.sbt we import the deps we need for that specific module. 
So our dependencies file has the following: 
```scala
val commonDeps = Seq( a )
val coreDeps = libraryDependcies ++= (commonDeps ++ Seq( b ))
val toolDeps = libraryDependcies ++= (commonDeps ++ Seq( c ))
```
so in core you import dependencies.coreDeps and so on.
Whe i run undeclaredCompileDependencies  i get the ones declared in commonDeps as undeclared in my dependencies.
Is this expected behaviour? If i move the dependencies declared in common deps inside the `Seq` declared in coreDeps undeclaredCompileDependencies doesn't warn about it.

Thanks.

**Comment by cb372** [comment] 2020-01-15 21:11
No, this is not expected behaviour.

I wrote a test but I was unable to reproduce the issue, so I'm going to close this. Please re-open if you can come up with a reproducer.

**Closed by cb372** 2020-01-15 21:11 UTC
